In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("stock_data.csv")
df.head()

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani

In [17]:
df = pd.read_csv("stock_data.csv", skiprows=1)
df.head()

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [18]:
df.isna().sum()

tickers    0
eps        0
revenue    0
price      0
people     0
dtype: int64

In [19]:
df = pd.read_csv("stock_data.csv", header = 1)
df.head()

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [20]:
df = pd.read_csv("stock_data.csv", header=1 , names=['stock_symbol', 'eps', 'revenue', 'price', 'people'])

In [21]:
df.head()

  stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [22]:
df = pd.read_csv("stock_data.csv", header=1 , names=['stock_symbol', 'eps', 'revenue', 'price', 'people'], nrows=3)

In [23]:
df.head()

  stock_symbol    eps  revenue  price      people
0        GOOGL  27.82       87    845  larry page
1          WMT   4.61      484     65        n.a.
2         MSFT  -1.00       85     64  bill gates

In [30]:
df = pd.read_csv("stock_data.csv", header=1 , na_values=
[
'n.a.' , -1 , 'not_available']
)

In [31]:
df.head()

  tickers            eps  revenue   price         people
0   GOOGL          27.82     87.0   845.0     larry page
1     WMT           4.61    484.0    65.0            NaN
2    MSFT            NaN     85.0    64.0     bill gates
3    RIL   not available     50.0  1023.0  mukesh ambani
4    TATA            5.6      NaN     NaN     ratan tata

In [32]:
df["pp"] = df["price"] - df["revenue"]

In [33]:
df.head()

  tickers            eps  revenue   price         people     pp
0   GOOGL          27.82     87.0   845.0     larry page  758.0
1     WMT           4.61    484.0    65.0            NaN -419.0
2    MSFT            NaN     85.0    64.0     bill gates  -21.0
3    RIL   not available     50.0  1023.0  mukesh ambani  973.0
4    TATA            5.6      NaN     NaN     ratan tata    NaN

In [35]:
df.to_csv("test.csv", index=False)

In [36]:
df = pd.read_excel("movies_db.xlsx","movies")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.